version: "3.1"

services:
  nginx:
    build: ./docker/nginx/
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    networks:
      - dockerlocal

  php:
    build: ./docker/php/
    volumes:
      - .:/var/www/html
    networks:
      - dockerlocal

networks:
  dockerlocal:
    driver: "bridge"
